// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef PERSON_ODB_H
#define PERSON_ODB_H

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "person.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>
#include <odb/view-image.hxx>
#include <odb/view-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // person
  //
  template <>
  struct class_traits< ::person >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::person >
  {
    public:
    typedef ::person object_type;
    typedef ::person* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // person_stat
  //
  template <>
  struct class_traits< ::person_stat >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::person_stat >
  {
    public:
    typedef ::person_stat view_type;
    typedef ::person_stat* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mssql/version.hxx>
#include <odb/mssql/forward.hxx>
#include <odb/mssql/binding.hxx>
#include <odb/mssql/mssql-types.hxx>
#include <odb/mssql/query.hxx>

namespace odb
{
  // person
  //
  template <typename A>
  struct query_columns< ::person, id_mssql, A >
  {
    // id
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        long unsigned int,
        mssql::id_bigint >::query_type,
      mssql::id_bigint >
    id_type_;

    static const id_type_ id;

    // first
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        ::std::string,
        mssql::id_string >::query_type,
      mssql::id_string >
    first_type_;

    static const first_type_ first;

    // last
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        ::std::string,
        mssql::id_string >::query_type,
      mssql::id_string >
    last_type_;

    static const last_type_ last;

    // age
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        short unsigned int,
        mssql::id_smallint >::query_type,
      mssql::id_smallint >
    age_type_;

    static const age_type_ age;
  };

  template <typename A>
  const typename query_columns< ::person, id_mssql, A >::id_type_
  query_columns< ::person, id_mssql, A >::
  id (A::table_name, "[id]", 0);

  template <typename A>
  const typename query_columns< ::person, id_mssql, A >::first_type_
  query_columns< ::person, id_mssql, A >::
  first (A::table_name, "[first]", 0, 512);

  template <typename A>
  const typename query_columns< ::person, id_mssql, A >::last_type_
  query_columns< ::person, id_mssql, A >::
  last (A::table_name, "[last]", 0, 512);

  template <typename A>
  const typename query_columns< ::person, id_mssql, A >::age_type_
  query_columns< ::person, id_mssql, A >::
  age (A::table_name, "[age]", 0);

  template <typename A>
  struct pointer_query_columns< ::person, id_mssql, A >:
    query_columns< ::person, id_mssql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::person, id_mssql >:
    public access::object_traits< ::person >
  {
    public:
    static const std::size_t batch = 1UL;

    static const bool rowversion = false;

    struct id_image_type
    {
      long long id_value;
      SQLLEN id_size_ind;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      SQLLEN id_size_ind;

      // first_
      //
      char first_value[513];
      SQLLEN first_size_ind;

      // last_
      //
      char last_value[513];
      SQLLEN last_size_ind;

      // age_
      //
      short age_value;
      SQLLEN age_size_ind;

      std::size_t version;

      mssql::change_callback change_callback_;

      mssql::change_callback*
      change_callback ()
      {
        return &change_callback_;
      }
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static void
    bind (mssql::bind*,
          image_type&,
          mssql::statement_kind);

    static void
    bind (mssql::bind*, id_image_type&);

    static void
    init (image_type&,
          const object_type&,
          mssql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mssql::object_statements<object_type> statements_type;

    typedef mssql::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::person, id_common >:
    public access::object_traits_impl< ::person, id_mssql >
  {
  };

  // person_stat
  //
  template <>
  class access::view_traits_impl< ::person_stat, id_mssql >:
    public access::view_traits< ::person_stat >
  {
    public:
    struct image_type
    {
      // count
      //
      long long count_value;
      SQLLEN count_size_ind;

      // min_age
      //
      short min_age_value;
      SQLLEN min_age_size_ind;

      // max_age
      //
      short max_age_value;
      SQLLEN max_age_size_ind;

      std::size_t version;

      mssql::change_callback change_callback_;

      mssql::change_callback*
      change_callback ()
      {
        return &change_callback_;
      }
    };

    typedef mssql::view_statements<view_type> statements_type;

    typedef mssql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static void
    bind (mssql::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 3UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::person_stat, id_common >:
    public access::view_traits_impl< ::person_stat, id_mssql >
  {
  };

  // person
  //
  // person_stat
  //
  struct access::view_traits_impl< ::person_stat, id_mssql >::query_columns:
    odb::pointer_query_columns<
      ::person,
      id_mssql,
      odb::access::object_traits_impl< ::person, id_mssql > >
  {
  };
}

#include "person_odb_inline.h"

#include <odb/post.hxx>

#endif // PERSON_ODB_H
